url: "https://amichiamoci.it"
baseurl: ""
title: "Amichiamoci"
lang: it-IT
repo_url:
plugins:
  - jekyll-sitemap

authors:
  - name: Riccardo Ciucci
    linkedin: https://www.linkedin.com/in/riccardo-ciucci-03bba8309/
    site: https://ciucci.dev
    roles: Sviluppatore, Amministratore
  - name: Leonardo Puccini
    linkedin: https://www.linkedin.com/in/leonardopuccini/
    roles: Sviluppatore
  - name: Andrea Panariello
    linkedin: https://www.linkedin.com/in/andreapanariello/
    roles: Amministratore

# Comment to hide the link
subscription_url: https://app.amichiamoci.it

logos:
  - year: 2025
    file: /assets/images/logos/2025.png
    motto: Un cammino di speranza per un futuro di Luce
  - year: 2024
    file: /assets/images/logos/2024.jpg
    motto: Dov'è odio, che io porti Amore
  - year: 2023
    file: /assets/images/logos/2023.svg
    motto: Piedi per terra, cuori nel Cielo
  - year: 2022
    file: /assets/images/logos/2022.svg
    motto: Prendete in mano la vostra vita e fatene un capolavoro
  - year: 2019
    file: /assets/images/logos/2019.jpg
    motto: Apri il cuore al mondo
  - year: 2018
    file: /assets/images/logos/2018.jpg
    motto: Niente riserve, più titolari
  - year: 2017
    file: /assets/images/logos/2017.jpg
    motto: Chiamati alla gioia
  - year: 2016
    file: /assets/images/logos/2016.jpg
    motto: Ama e dillo con la vita
  - year: 2015
    file: /assets/images/logos/2015.jpg
    motto: Keep calm and rallegriamoci
  - year: 2014
    file: /assets/images/logos/2014.jpg
    motto: Il vero potere è il servizio
  - year: 2013
    file: /assets/images/logos/2013.jpg
    motto: Rispondi alla chiamata
  - year: 2012
    file: /assets/images/logos/2012.jpg
    motto: È più bello insieme
  - year: 2011
    file: /assets/images/logos/2011.jpg
    motto: Ascolta la mia voce
  - year: 2010
    file: /assets/images/logos/2010.jpg
    motto: Radicati in Cristo, saldi nella Fede
  - year: 2009
    file: /assets/images/logos/2009.jpg
    motto: Trova il Tempo...
  - year: 2008
    file: /assets/images/logos/2008.jpg
    motto: Avrete la forza dallo Spirito Santo
  - year: 2007
    file: /assets/images/logos/2007.jpg
  - year: 2006
    file: /assets/images/logos/2006.jpg

events:
  - name: Festa Iniziale
    image: /assets/images/events/festa-iniziale.jpg
    link: /events/opening-feast
    brief: Una festa per inaugurare la nuova edizione di Amichiamoci.
  - name: Caccia al Tesoro
    image: /assets/images/events/caccia-al-tesoro.jpg
    link: /events/treasure-hunt
    brief: Intrigante caccia (a premi) per le vie della città.
  - name: Cena con Delitto
    image: /assets/images/events/cena-con-delitto.jpg
    link: /events/murder-mistery-dinner
    brief: Cena con delitto a squadre. Troverete il colpevole?
  - name: Biliardino e Ping Pong
    image: 
    link: /events/table-sports
    brief: Un pomeriggio all'insegna degli sport da tavolo
  - name: Ponci e Gio'i
    image: 
    link: /events/table-games
    brief: Una serata di giochi da tavolo in compagnia
  - name: Santa Messa
    image: /assets/images/events/santa-messa.jpg
    link: /events/holy-mass
    brief: La Santa Messa di Amichiamoci, siete tutti invitati!
  - name: Veglia di Preghiera
    image: /assets/images/events/veglia-di-preghiera.jpg
    link: /events/prayer-vigil
    brief: Un momento di preghiera e di riflessione	insieme.
  - name: Festa finale
    image: /assets/images/events/festa-finale.jpg
    link: /events/closing-feast
    brief: Musica, cibo e divertimento per chiudere in bellezza.